name: Build  Next.js Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Next.js Project

    strategy:
      matrix:
        node-version: [14, 18]
        react-version: [16.13.1, 17.0.1, 17.0.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Build the Next.js project
      run: |
        npm run build


