name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-localhost:
    runs-on: ubuntu-latest
    steps:
      - name: CHeckout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        
      - name: Run Localhost and cypress
        run: npm run dev & npx cypress run
        
        
  run-Cypress:
    runs-on: ubuntu-latest
    needs: run-localhost
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        
      - name: Wait for localhost
        run: npx wait-on http://localhost:3000
        
      - name: Run Cypress Tests
        run: npx cypress run
